[package]
name = "iroha_python"
version = "0.1.0"
authors = ["Iroha 2 team <https://github.com/orgs/soramitsu/teams/iroha2>"]
edition = "2021"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = ["generate"]

[lib]
name = "iroha2"
crate-type = ["cdylib"]

[dependencies]
iroha_client = { git = "https://github.com/QuentinI/iroha", branch = "2103-additional-queries" }
iroha_crypto = { git = "https://github.com/QuentinI/iroha", branch = "2103-additional-queries" }
iroha_data_model = { git = "https://github.com/QuentinI/iroha", branch = "2103-additional-queries" }
iroha_version = { git = "https://github.com/QuentinI/iroha", branch = "2103-additional-queries" }

color-eyre = "0.5"
parity-scale-codec = "2.2"
pyo3 = { version = "0.15.0", features = ["extension-module"] }
pythonize = "0.15.0"
serde = "1"
serde_json = "1"
