[package]
name = "iroha_python"
version = "0.1.0"
authors = ["Iroha 2 team <https://github.com/orgs/soramitsu/teams/iroha2>"]
edition = "2018"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = ["generate"]

[lib]
name = "iroha2"
crate-type = ["cdylib"]

[dependencies]
iroha_client = { git = "https://github.com/hyperledger/iroha", branch = "iroha2-dev" }
iroha_crypto = { git = "https://github.com/hyperledger/iroha", branch = "iroha2-dev" }
iroha_error = { git = "https://github.com/hyperledger/iroha", branch = "iroha2-dev" }
iroha_data_model = { git = "https://github.com/hyperledger/iroha", branch = "iroha2-dev" }

pythonize = { git = "https://github.com/i1i1/pythonize", branch = "dict" }
parity-scale-codec = "2.2"
pyo3 = { version = "0.14", features = ["extension-module"] }
serde = "1"
serde_json = "1"
