version: 2

jobs:
  build:
    docker:
      - image: alpine:3.5
    working_directory: /root

    steps:
      - run:
          name: Install system-wide packages
          command: apk add --no-cache --quiet cmake curl g++ git ninja openssh python2-dev python3-dev

      - checkout

      - run:
          name: Install flatc
          command: |
            set -ex
            FBVER='1.6.0'
            curl --location --silent https://github.com/google/flatbuffers/archive/v${FBVER}.tar.gz | tar -xz
            cmake -GNinja -Hflatbuffers-${FBVER} -Bflatbuffers-build
            cmake --build flatbuffers-build --target flatc
            cp flatbuffers-build/flatc /usr/local/bin
            rm -rf flatbuffers-${FBVER} flatbuffers-build

      - run:
          name: Install tox
          command: pip3 --quiet install tox

      - run:
          name: Generate FlatBufers schema
          command: python3 setup.py genfbs

      - run:
          name: Run tests
          command: tox

